### ISSUE TITLE
Incompatible with other libs

### ISSUE THREAD

**Issue by Evanfeenstra** [warpr/zbase32#9]
This lib is not compatible with others like https://github.com/tv42/zbase32

Just try encoding the bytes [1,2,3,4,5,6,7,8]... `tv42/zbase32` returns `yrbygbyfyadoo` but this lib returns `ynyodyonocbae`

Which one is "correct"?

**Comment by warpr** [comment]
@Evanfeenstra sorry for the late response, I didn't see your message earlier.

My code seems to match python:

```py
Python 3.10.5 (main, Jul 23 2022, 03:00:09) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zbase32
>>> zbase32.encode(b'hello')
'pb1sa5dx'
>>> zbase32.decode('pb1sa5dx')
b'hello'
```

The above is using [python-zbase32-0.1.1](https://pypi.org/project/python-zbase32/).

The go library you linked says it has been tested against https://pypi.org/project/zbase32/ , but that library hasn't been updated since 2012, so I wasn't able to easily verify that.
